name: Update recent blog post
on:
  schedule:
    # Runs every day at 3pm UTC (11pm SG)
    # cron: `0 15 * * *`
    - cron: '12 8 * * *'

jobs:
  pull_blog_rss:
    name: Update with latest blog posts
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Get RSS Feed
        uses: kohrongying/readme-the-rss@master
        with:
          feed_url: https://www.hacker-cube.com/atom.xml
          count: 6 # default 5
      - name: Commit file changes
        run: |
            git config --global user.name 'Phoenix'
            git config --global user.email 'Phoenix500526@163.com'
            git pull --rebase https://github.com/Phoenix500526/Phoenix500526.git master
            git add .
            git diff --quiet --cached || git commit -m "Update README"    
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
