name: Update My Recent Blog Post
on:
  schedule: # Run workflow automatically
    - cron: '0 0 * * *' 
  workflow_dispatch: # Run workflow manually (without waiting for the cron to be called), through the Github Actions Workflow page directly
jobs:
  update-readme-with-blog:
    name: Update this repo's README with latest blog posts
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: gautamkrishnar/blog-post-workflow@master
        with:
          date_format: fullDate 
          template: "$newline* [$title]($url) - $date"
          feed_list: "https://www.hacker-cube.com/atom.xml"
